cosas

diff --git a/azure-devops/00-deploy-infra.yml b/azure-devops/00-deploy-infra.yml
--- a/azure-devops/00-deploy-infra.yml
+++ b/azure-devops/00-deploy-infra.yml
@@ -96,9 +96,9 @@ steps:
   condition: always()
 
 - script: |
-    sed -i "s/redis_host:.*/redis_host: $ELASTICACHE_DEV_ENDPOINT/g" helm/my-app/backend/environments/values-dev.yaml
-    sed -i "s/redis_host:.*/redis_host: $ELASTICACHE_STAGE_ENDPOINT/g" helm/my-app/backend/environments/values-stage.yaml
-    sed -i "s/redis_host:.*/redis_host: $ELASTICACHE_PROD_ENDPOINT/g" helm/my-app/backend/environments/values-prod.yaml
+    sed -i "s/redis_host:.*/redis_host: $(echo $ELASTICACHE_DEV_ENDPOINT)/g" helm/my-app/backend/environments/values-dev.yaml
+    sed -i "s/redis_host:.*/redis_host: $(echo $ELASTICACHE_STAGE_ENDPOINT)/g" helm/my-app/backend/environments/values-stage.yaml
+    sed -i "s/redis_host:.*/redis_host: $(echo $ELASTICACHE_PROD_ENDPOINT)/g" helm/my-app/backend/environments/values-prod.yaml
   displayName: 'Modify values for each environment'
   condition: always()
 
@@ -134,37 +134,37 @@ steps:
   displayName: 'Configure AWS Profile'
   condition: always()
 
-- script: |
-    ZONE_ID=$(aws route53 list-hosted-zones-by-name --output json --dns-name "$(DOMAIN)" |  jq -r '.HostedZones[0].Id' | cut -d'/' -f3)
-    NS_VALUES=$(aws route53 list-resource-record-sets --hosted-zone-id $ZONE_ID | jq -r '.ResourceRecordSets[] | select(.Type=="NS") .ResourceRecords[].Value')
-    FORMATTED_NS_VALUES=$(echo "$NS_VALUES" | sed 's/\.$//;s/^/Name=/')
-    SINGLE_LINE_NS_VALUES=$(echo "${FORMATTED_NS_VALUES}" | tr '\n' ' ')
-    echo $SINGLE_LINE_NS_VALUES
-    aws route53domains update-domain-nameservers --region us-east-1 --domain-name $(DOMAIN) --nameservers $(echo $SINGLE_LINE_NS_VALUES)
+# - script: |
+#     ZONE_ID=$(aws route53 list-hosted-zones-by-name --output json --dns-name "$(DOMAIN)" |  jq -r '.HostedZones[0].Id' | cut -d'/' -f3)
+#     NS_VALUES=$(aws route53 list-resource-record-sets --hosted-zone-id $ZONE_ID | jq -r '.ResourceRecordSets[] | select(.Type=="NS") .ResourceRecords[].Value')
+#     FORMATTED_NS_VALUES=$(echo "$NS_VALUES" | sed 's/\.$//;s/^/Name=/')
+#     SINGLE_LINE_NS_VALUES=$(echo "${FORMATTED_NS_VALUES}" | tr '\n' ' ')
+#     echo $SINGLE_LINE_NS_VALUES
+#     aws route53domains update-domain-nameservers --region us-east-1 --domain-name $(DOMAIN) --nameservers $(echo $SINGLE_LINE_NS_VALUES)
 
-    # Enabling DNSSEC signing will fail if we've just updated our domain's name servers, so we'll keep trying every one minute.
-    while true; do
-      set +e
-      aws route53 enable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
-      result=$?
-      set -e
-      if [ $result -ne 0 ]; then
-        echo "Attempt failed. Waiting for 1 minute before retrying..."
-        sleep 60
-      else
-        echo "DNSSEC signing enabled successfully."
-        break
-      fi
-    done
+#     # Enabling DNSSEC signing will fail if we've just updated our domain's name servers, so we'll keep trying every one minute.
+#     while true; do
+#       set +e
+#       aws route53 enable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
+#       result=$?
+#       set -e
+#       if [ $result -ne 0 ]; then
+#         echo "Attempt failed. Waiting for 1 minute before retrying..."
+#         sleep 60
+#       else
+#         echo "DNSSEC signing enabled successfully."
+#         break
+#       fi
+#     done
 
-    aws --region us-east-1 route53 get-dnssec --hosted-zone-id $ZONE_ID | jq -r '.KeySigningKeys[0].PublicKey' > public-signing-key.txt
-  displayName: 'Configure domain registrar name servers and enable DNSSEC signing on hosted zone'
-  condition: always()
+#     aws --region us-east-1 route53 get-dnssec --hosted-zone-id $ZONE_ID | jq -r '.KeySigningKeys[0].PublicKey' > public-signing-key.txt
+#   displayName: 'Configure domain registrar name servers and enable DNSSEC signing on hosted zone'
+#   condition: always()
 
-- task: PublishBuildArtifacts@1
-  displayName: 'Export SSH command'
-  condition: always()
-  inputs:
-    PathtoPublish: 'public-signing-key.txt'
-    ArtifactName: 'Public singning key'
-    publishLocation: 'Container'
+# - task: PublishBuildArtifacts@1
+#   displayName: 'Export SSH command'
+#   condition: always()
+#   inputs:
+#     PathtoPublish: 'public-signing-key.txt'
+#     ArtifactName: 'Public singning key'
+#     publishLocation: 'Container'
