test new deploy infra

diff --git a/azure-devops/05-destroy-all-the-things.yml b/azure-devops/05-destroy-all-the-things.yml
--- a/azure-devops/05-destroy-all-the-things.yml
+++ b/azure-devops/05-destroy-all-the-things.yml
@@ -93,20 +93,40 @@ jobs:
       echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
     displayName: 'Configure AWS Profile'
 
-  - script: |
-      echo "Waiting for 15 minutes..."
-      echo "Why?"
-      echo "Well, after deleting the DNSSEC key from the domain registrar we need to wait the TTL of the DS record before disabling DNSSEC signing."
-      echo "The default TTL of the DS record is 900 seconds (15 minutes)."
-      echo "Assuming you've just deleted the DNSSEC key from the domain registrar, we'll wait the default TTL before running the 'aws route53 disable-hosted-zone-dnssec' command."
-      echo "Go grab yourself a cup of coffee..."
-      sleep 900
-    displayName: 'Wait 15 Minutes'
+  # - script: |
+  #     echo "Waiting for 15 minutes..."
+  #     echo "Why?"
+  #     echo "Well, after deleting the DNSSEC key from the domain registrar we need to wait the TTL of the DS record before disabling DNSSEC signing."
+  #     echo "The default TTL of the DS record is 900 seconds (15 minutes)."
+  #     echo "Assuming you've just deleted the DNSSEC key from the domain registrar, we'll wait the default TTL before running the 'aws route53 disable-hosted-zone-dnssec' command."
+  #     echo "Go grab yourself a cup of coffee..."
+  #     sleep 900
+  #   displayName: 'Wait 15 Minutes'
+
+  # - script: | 
+  #     ZONE_ID=$(aws route53 list-hosted-zones-by-name --output json --dns-name "$(DOMAIN)" |  jq -r '.HostedZones[0].Id' | cut -d'/' -f3)
+  #     aws route53 disable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
+  #   displayName: 'Disable DNSSEC signing on hosted zone'
 
   - script: | 
       ZONE_ID=$(aws route53 list-hosted-zones-by-name --output json --dns-name "$(DOMAIN)" |  jq -r '.HostedZones[0].Id' | cut -d'/' -f3)
-      aws route53 disable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
+      
+      # Enabling DNSSEC signing will fail if we've juts updated our domain's name servers, so we'll keep trying every one minute.
+      while true; do
+        set +e
+        aws route53 disable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
+        result=$?
+        set -e
+        if [ $result -ne 0 ]; then
+          echo "Attempt failed. Waiting for 1 minute before retrying..."
+          sleep 60
+        else
+          echo "DNSSEC signing enabled successfully."
+          break
+        fi
+      done
     displayName: 'Disable DNSSEC signing on hosted zone'
+
 
   - task: TerraformInstaller@1
     displayName: Install terraform
