setup

diff --git a/azure-devops/05-destroy-all-the-things.yml b/azure-devops/05-destroy-all-the-things.yml
--- a/azure-devops/05-destroy-all-the-things.yml
+++ b/azure-devops/05-destroy-all-the-things.yml
@@ -4,12 +4,12 @@ trigger: none
 
 parameters:
   - name: DELETED_KEY_FROM_DOMAIN
-    displayName: "IMPORTANT!!! Have you deleted the DNSSEC key from the domain? If you haven't 'terraform destroy' won't run and AWS resources will remain active."
+    displayName: "IMPORTANT!!! Have you deleted the DNSSEC key from the domain registrar? If you haven't 'terraform destroy' will fail. Type 'yes' to proceed."
     type: string
-    default: 'No'
-    values:
-    - 'Yes'
-    - 'No'
+    # default: 'No'
+    # values:
+    # - 'Yes'
+    # - 'No'
 
 variables:
   - group: aws-keys
@@ -29,7 +29,7 @@ pool:
 
 jobs:
 - job: DeleteK8SResources
-  # condition: eq('${{ parameters.DELETED_KEY_FROM_DOMAIN }}', 'Yes')
+  condition: eq('${{ parameters.DELETED_KEY_FROM_DOMAIN }}', 'yes')
   displayName: 'Delete Kubernetes Resources'
   steps:
 
@@ -68,20 +68,21 @@ jobs:
 
   # There's a specific order we need to follow for things to go smoothly, read the "echo's" to understand.
   - script: | 
-      echo "########################################################################"
       echo "Before deleting all applications we eliminate the App of Apps."
       echo "If we don't, it will try to re-deploy the other applications along with their ingresses."
       echo "This would automatically create untracked AWS Application Load Balancers and mess up the terraform destroy."
       echo "########################################################################"
       kubectl delete -n argocd applications.argoproj.io argocd-apps
 
-      echo "########################################################################"
+      echo " "
+      echo " "
       echo "We also to remove the finalizers from the Kiali CR for deletion to be successful. It's a known issue:"
       echo "https://kiali.io/docs/installation/installation-guide/install-with-helm/#known-problem-uninstall-hangs-unable-to-delete-the-kiali-cr"
       echo "########################################################################"
       kubectl patch kiali kiali -n service-mesh -p '{"metadata":{"finalizers": []}}' --type=merge
 
-      echo "########################################################################"
+      echo " "
+      echo " "
       echo "We delete all apps except External-DNS. Why?"
       echo "We need External-DNS to notice there are no ingress objects anymore so it can go and remove the DNS records belonging to those deleted ingresses."
       echo "If these records don't get removed, the terraform destroy will fail."
@@ -89,12 +90,14 @@ jobs:
       echo "########################################################################"
       kubectl get applications.argoproj.io -n argocd -o name | grep -v "external-dns" | xargs kubectl delete -n argocd
 
-      echo "########################################################################"
+      echo " "
+      echo " "
       echo "We uninstall ArgoCD. Deleting its application doesn't really remove it."
       echo "########################################################################"
       helm uninstall -n argocd argocd
       
-      echo "########################################################################"
+      echo " "
+      echo " "
       echo "Finally, we can remove external-dns."
       echo "We will give it a minute first so it can notice the abscence of ingress objects and deletes the corrsponding DNS records."
       echo "Every how long External-DNS checks for changes can be specified in it's values-custom.yaml."
@@ -120,10 +123,10 @@ jobs:
   displayName: 'Delete AWS Infrastructure'
   dependsOn: DeleteK8SResources
   steps:
-  # This step it only to display the pipeline as "Failed" if parameter DELETED_KEY_FROM_DOMAIN is "No". Without this, the pipeline will result as successful which may lead to confusion.
-  - ${{ if eq(parameters.DELETED_KEY_FROM_DOMAIN, 'No') }}:
-    - script: echo "DELETED_KEY_FROM_DOMAIN is set to No, failing the pipeline." && exit 1
-      displayName: Fail the pipeline if DELETED_KEY_FROM_DOMAIN is No
+  # # This step it only to display the pipeline as "Failed" if parameter DELETED_KEY_FROM_DOMAIN is "No". Without this, the pipeline will result as successful which may lead to confusion.
+  # - ${{ if eq(parameters.DELETED_KEY_FROM_DOMAIN, 'No') }}:
+  #   - script: echo "DELETED_KEY_FROM_DOMAIN is set to No, failing the pipeline." && exit 1
+  #     displayName: Fail the pipeline if DELETED_KEY_FROM_DOMAIN is No
 
   - script: | 
       mkdir ~/.aws
