cambio a keys de sendati

diff --git a/azure-devops/05-destroy-all-the-things.yml b/azure-devops/05-destroy-all-the-things.yml
--- a/azure-devops/05-destroy-all-the-things.yml
+++ b/azure-devops/05-destroy-all-the-things.yml
@@ -136,24 +136,24 @@ jobs:
   #     aws route53 disable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
   #   displayName: 'Disable DNSSEC signing on hosted zone'
 
-  - script: | 
-      ZONE_ID=$(aws route53 list-hosted-zones-by-name --output json --dns-name "$(DOMAIN)" |  jq -r '.HostedZones[0].Id' | cut -d'/' -f3)
+  # - script: | 
+  #     ZONE_ID=$(aws route53 list-hosted-zones-by-name --output json --dns-name "$(DOMAIN)" |  jq -r '.HostedZones[0].Id' | cut -d'/' -f3)
       
-      # Disabling DNSSEC signing will fail if we've just deleted the DNSSEC key from the domain, so we'll keep trying every one minute.
-      while true; do
-        set +e
-        aws route53 disable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
-        result=$?
-        set -e
-        if [ $result -ne 0 ]; then
-          echo "Attempt failed. Waiting for 1 minute before retrying..."
-          sleep 60
-        else
-          echo "DNSSEC signing disabled successfully."
-          break
-        fi
-      done
-    displayName: 'Disable DNSSEC signing on hosted zone'
+  #     # Disabling DNSSEC signing will fail if we've just deleted the DNSSEC key from the domain, so we'll keep trying every one minute.
+  #     while true; do
+  #       set +e
+  #       aws route53 disable-hosted-zone-dnssec --region us-east-1 --hosted-zone-id $ZONE_ID
+  #       result=$?
+  #       set -e
+  #       if [ $result -ne 0 ]; then
+  #         echo "Attempt failed. Waiting for 1 minute before retrying..."
+  #         sleep 60
+  #       else
+  #         echo "DNSSEC signing disabled successfully."
+  #         break
+  #       fi
+  #     done
+  #   displayName: 'Disable DNSSEC signing on hosted zone'
 
 
   - task: TerraformInstaller@1
